[project]
name = "programmieruebung2_Haas_Hager"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
<<<<<<< HEAD
    {name = "Mani5623", email = "hm9703@mci4me.at"},
=======
    {name = "ha1267", email = "ha1267@mci4me.at"},
>>>>>>> 287122f95864788cfad30628103b2e7fcd384020
]
dependencies = ["numpy>=2.2.5", "matplotlib>=3.10.1"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
